#######################
#  Created on: May 16, 2024
#  Author: Adriana GV
#######################

# Cameras info
camera0: ZED
serial_num: 23542
calibration: zed_data.json
depth_correction_file: depth_correction_params.yml
# Ground Truth 

# Main paths
my_sdk: /home/agv/ZED/Calibration_FVV
working_path: /home/agv/ZED/
dim_path: /home/agv/Calib_models/deep-image-matching
scene: suelo_fvv
frames_folder: images
depth_frames_folder: depth_frames
dim_results_path: results_superpoint+superglue_bruteforce_quality_highest
dim_matches: matches_dim

# BETTER NOT TOUCH (Files & directries structutre)
# Outputs paths & files
out_path: output
sfm_data_scaled: sfm_data_scaled.json
sfm_data: sfm_data.json
init_sfm_data: sfm_data_no_poses.json

# Error Study directories & files (Usually inside output directory)
reprojection_path: reprojection
reprojection_file: reproyection_study.json
reprojection_file_checker: reproyection_study_checker.json
plane_path: plane_3D
plane_file: plane_data.json

# UID & GID
user_id: 1016
user_group: 1016