#######################
#  Created on: May 16, 2024
#  Author: Adriana GV
#######################

# Camera info
camera: ZED
serial_num: 23542
calibration: zed_data.json
# Ground Truth 
# Main paths
working_path: /media/agv/JesusGTI3/ZED_Recordings/svo
scene: sala_yo
frames_folder: colour_frames
depth_frames_folder: depth_frames
# UID & GID
user_id: 1016
user_group: 1016
# Select_frames script variable
frames_to_rm: 4
# Corners info script variable
num_corners_x: 10
num_corners_y: 5
length_unit: 128 # This is the SIFT method length. If SURF is used, 64
dist_mm: 101.6 # CheckerBoard C building is 28 mm | D buildin is 101.6 mm
# BETTER NOT TOUCH (Files & directries structutre)
# Outputs paths & files
out_path: output
sfm_data_scaled: sfm_data_scaled.json
sfm_data: sfm_data.json
# Checker Reconstruction (Known Poses)
known_poses: Reconstruction_for_known
scale_data: rescale_data
known_sfm_data: cloud_and_poses.json
scaled_known_sfm_data: cloud_and_poses_scaled.json
measures_file: measures_data.json
scales_file: scale_data.json
# Error Study directories & files (Usually inside output directory)
reprojection_path: reprojection
reprojection_file: reproyection_study.json
reprojection_file_checker: reproyection_study_checker.json
plane_path: plane_3D
plane_file: plane_data.json
depth_path: depth_study
depth_file: depth_study.json
ratios_file: ratios_study.json
calibration_path: Calibration
err_params_file: DepthTransformationParameters.txt
calib_file: synthesisConfiguration_original.yml
