calibration: svo_info.json
calibration_path: Calibration
camera: ZED2
depth_file: depth_study.json
depth_frames_folder: depth_frames
depth_path: depth_study
device_path: /home/agv/Calibration
dist_mm: 101.6
dockers_path: ZED
err_params_file: DepthTransformationParameters.yml
extrinsics_file: extrinsics.json
frames_folder: colour_frames
known_poses: Reconstruction_for_known
known_sfm_data: cloud_and_poses.json
length_unit: 128
measures_file: measures_data.json
num_corners_x: 10
num_corners_y: 5
out_path: output
plane_file: plane_data.json
plane_path: plane_3D
ratios_file: ratios_study.json
reprojection_file: reproyection_study.json
reprojection_file_checker: reproyection_study_checker.json
reprojection_path: reprojection
scale_data: rescale_data
scaled_known_sfm_data: cloud_and_poses_scaled.json
scales_file: scale_data.json
scene: prueba_script
serial_num: '29752001'
sfm_data: sfm_data.json
sfm_data_scaled: sfm_data_scaled.json
svo_file: prueba_script.svo
user_group: 1016
user_id: 1016
working_path: ZED/ZED2_29752001
