#######################
#  Created on: May 16, 2024
#  Author: Adriana GV
#######################


# Configurable paths
device_path: /media/agv/JesusGTI4/cam_sn127
dockers_path: ZED
# Configurable ZED SDK version
zed_sdk_v: v3 # If a higher SDK version is used, just change to v3 to v4
# Configurable params -> Corners info script variable
num_corners_x: 10
num_corners_y: 5
length_unit: 128 # This is the SIFT method length. If SURF is used, 64
dist_mm: 101.6 # CheckerBoard C building is 28 mm | D buildin is 101.6 mm

# BETTER NOT TOUCH (Files & directries structutre)
# Main paths
working_path: /home/agv/ZED
scene: all
frames_folder: colour_frames
depth_frames_folder: depths
# Outputs paths & files
out_path: output
sfm_data_scaled: sfm_data_scaled.json
sfm_data: sfm_data.json
# Checker Reconstruction (Known Poses)
known_poses: Reconstruction_for_known
scale_data: rescale_data
known_sfm_data: cloud_and_poses.json
scaled_known_sfm_data: cloud_and_poses_scaled.json
measures_file: measures_data.json
scales_file: scale_data.json
# Error Study directories & files (Usually inside output directory)
reprojection_path: reprojection
reprojection_file: reproyection_study.json
reprojection_file_checker: reproyection_study_checker.json
plane_path: plane_3D
plane_file: plane_data.json
calibration_path: Calibration
err_params_file: DepthTransformationParameters.json
image_list: lists.txt

# Permisions changes for docker and PC -> UID & GID 
user_id: 1016
user_group: 1016